from __future__ import annotations


class LocalizationService:
    def __init__(self) -> None:
        self._translations = {
            "en": {
                "app_title": "Voodoo Loader",
                "menu_app": "App",
                "menu_file": "File",
                "menu_downloads": "Downloads",
                "menu_view": "View",
                "menu_settings": "Settings",
                "menu_settings_open": "Open settings",
                "menu_import_txt": "Import .txt",
                "menu_exit": "Exit",
                "menu_language": "Language",
                "lang_en": "English",
                "lang_ru": "Русский",
                "ready": "Ready",
                "queue_started": "Queue started",
                "queue_finished": "Queue finished",
                "queue_stopped": "Queue stopped",
                "queue_already_running": "Queue already running. Add more links to enqueue.",
                "queue_empty": "No queued items to download.",
                "queue_group_title": "Download queue",
                "queue_select_all": "Select all",
                "queue_select_item": "Select",
                "queue_select_col": "Select",
                "queue_url_col": "File",
                "queue_status_col": "Status",
                "queue_progress_col": "Progress",
                "queue_speed_col": "Speed",
                "queue_eta_col": "ETA",
                "queue_total_size_col": "Total size",
                "queue_priority_col": "Priority",
                "destination_required": "Choose destination folder first.",
                "destination_group_title": "Destination",
                "speed_group_title": "Speed",
                "speed_preset_label": "Preset",
                "speed_hint": "Preset: {preset}",
                "resume_label": "Continue / Resume (-c)",
                "resume_hint": "Continue/resume means aria2 will continue partial files instead of restarting.",
                "progress_group_title": "Progress",
                "progress_more": "More",
                "progress_less": "Less",
                "aria2_not_found_title": "aria2 not found",
                "aria2_not_found_prompt": "aria2c is missing. Download and bootstrap automatically now?",
                "aria2_bootstrap_failed": "aria2c not found and bootstrap failed or canceled.",
                "import_error": "Import error",
                "queue_info": "Queue",
                "exit_title": "Exit",
                "exit_running_prompt": "Downloads are still running. Stop downloads and exit?",
                "cmd_preview_empty": "Queue is empty.",
                "settings_saved": "Max simultaneous downloads: {value}",
                "status_added_running": "Added new items to running queue",
                "unlimited_with_zero": "Unlimited (0)",
                "progress_current_item": "Current item: {value}",
                "progress_downloaded_total": "Downloaded / Total: {value}",
                "progress_remaining": "Remaining: {value}",
                "progress_speed": "Speed: {value}",
                "progress_eta": "ETA: {value}",
                "progress_none": "No active transfer",
                "progress_na": "-",
                "retry_selected_none": "No retryable selected items.",
                "retry_selected_done": "Retried selected items: {count}",
                "retry_all_none": "No failed/canceled items to retry.",
                "retry_all_done": "Retried all failed/canceled items: {count}",
                "remove_selected_none": "No removable selected items.",
                "remove_selected_done": "Removed selected items: {count}",
                "remove_failed_none": "No failed/canceled items to remove.",
                "remove_failed_done": "Removed failed/canceled items: {count}",
                "filename_placeholder": "Custom file name (single download only)",
                "filename_ignored_multi": "Custom file name is applied only when a single queued item is downloaded.",
                "auth_group_title": "Authentication (optional)",
                "auth_mode_label": "Auth mode",
                "auth_mode_none": "No auth",
                "auth_mode_token": "Token + headers",
                "auth_mode_basic": "Login/password",
                "auth_bearer_label": "Bearer token",
                "auth_show_token": "Show token",
                "auth_remember_token": "Remember token",
                "auth_remember_username": "Remember username",
                "auth_username_label": "Username",
                "auth_password_label": "Password",
                "auth_headers_label": "Custom headers",
                "auth_headers_placeholder": "Custom headers, one per line (Example: Cookie: abc=1)",
                "auth_mode_help_none": "Authentication is disabled. Enable it only when source requires access.",
                "auth_mode_help_token": "Provide bearer token and/or custom headers required by the source.",
                "auth_mode_help_basic": "Provide login/password required by the source.",
                "auth_show_password": "Show password",
                "auth_validation_title": "Authentication",
                "auth_validation_token_or_header_required": "Enter token or at least one custom header for this auth mode.",
                "auth_validation_username_required": "Enter username for login/password mode.",
                "auth_validation_password_required": "Enter password for login/password mode.",
                "auth_open_settings_hint": "Open Settings to edit authentication parameters.",
                "action_start": "Start",
                "action_stop": "Stop",
                "action_preview": "Preview command",
                "action_retry_selected": "Retry selected",
                "action_retry_all": "Retry all failed/canceled",
                "action_remove_selected": "Remove selected",
                "action_remove_failed": "Remove failed/canceled",
                "action_clear_queue": "Clear queue",
                "action_open_file": "Open file",
                "action_open_folder": "Open folder",
                "action_priority": "Priority",
                "priority_high": "High",
                "priority_medium": "Medium",
                "priority_low": "Low",
                "priority_updated": "Updated priority for {count} item(s): {priority}",
                "open_file_missing": "Downloaded file was not found.",
                "open_folder_missing": "Destination folder was not found.",
                "view_toggle_logs": "Show logs",
                "view_sort_by_date": "Sort by date added",
                "view_sort_by_extension": "Sort by extension",
                "view_sort_by_priority": "Sort by priority",
            },
            "ru": {
                "app_title": "Voodoo Loader",
                "menu_app": "Приложение",
                "menu_file": "Файл",
                "menu_downloads": "Закачки",
                "menu_view": "Вид",
                "menu_settings": "Настройки",
                "menu_settings_open": "Открыть настройки",
                "menu_import_txt": "Импорт .txt",
                "menu_exit": "Выход",
                "menu_language": "Язык",
                "lang_en": "English",
                "lang_ru": "Русский",
                "ready": "Готово",
                "queue_started": "Очередь запущена",
                "queue_finished": "Очередь завершена",
                "queue_stopped": "Очередь остановлена",
                "queue_already_running": "Очередь уже запущена. Добавляйте ссылки для догрузки.",
                "queue_empty": "В очереди нет задач для скачивания.",
                "queue_group_title": "Очередь закачек",
                "queue_select_all": "Выбрать всё",
                "queue_select_item": "Выбрать",
                "queue_select_col": "Выбор",
                "queue_url_col": "Файл",
                "queue_status_col": "Статус",
                "queue_progress_col": "Прогресс",
                "queue_speed_col": "Скорость",
                "queue_eta_col": "ETA",
                "queue_total_size_col": "Общий вес",
                "queue_priority_col": "Приоритет",
                "destination_required": "Сначала выберите папку загрузки.",
                "destination_group_title": "Папка загрузки",
                "speed_group_title": "Пресеты скорости",
                "speed_preset_label": "Пресет",
                "speed_hint": "Пресет: {preset}",
                "resume_label": "Продолжить / Возобновить (-c)",
                "resume_hint": "При включении aria2 продолжает частично скачанные файлы, а не начинает заново.",
                "progress_group_title": "Прогресс",
                "aria2_not_found_title": "aria2 не найден",
                "aria2_not_found_prompt": "aria2c не найден. Скачать и установить автоматически?",
                "aria2_bootstrap_failed": "aria2c не найден, автоустановка не выполнена или отменена.",
                "import_error": "Ошибка импорта",
                "queue_info": "Очередь",
                "exit_title": "Выход",
                "exit_running_prompt": "Есть активные загрузки. Остановить и выйти?",
                "cmd_preview_empty": "Очередь пуста.",
                "settings_saved": "Максимум одновременных загрузок: {value}",
                "status_added_running": "Новые ссылки добавлены в активную очередь",
                "unlimited_with_zero": "Без ограничений (0)",
                "progress_current_item": "Текущая загрузка: {value}",
                "progress_downloaded_total": "Скачано / Всего: {value}",
                "progress_remaining": "Осталось: {value}",
                "progress_speed": "Скорость: {value}",
                "progress_eta": "ETA: {value}",
                "progress_none": "Нет активной загрузки",
                "progress_na": "-",
                "retry_selected_none": "Нет выбранных задач для повтора.",
                "retry_selected_done": "Повторно запущено выбранных задач: {count}",
                "retry_all_none": "Нет ошибок/отмен для повтора.",
                "retry_all_done": "Повторно запущено ошибок/отмен: {count}",
                "remove_selected_none": "Нет выбранных задач для удаления.",
                "remove_selected_done": "Удалено выбранных задач: {count}",
                "remove_failed_none": "Нет ошибок/отмен для удаления.",
                "remove_failed_done": "Удалено ошибок/отмен: {count}",
                "filename_placeholder": "Свое имя файла (только для одной загрузки)",
                "filename_ignored_multi": "Свое имя файла применяется только при загрузке одного элемента очереди.",
                "auth_group_title": "Авторизация (опционально)",
                "auth_mode_label": "Режим авторизации",
                "auth_mode_none": "Без авторизации",
                "auth_mode_token": "Токен + заголовки",
                "auth_mode_basic": "Логин/пароль",
                "auth_bearer_label": "Bearer token",
                "auth_show_token": "Показать токен",
                "auth_remember_token": "Запомнить токен",
                "auth_remember_username": "Запомнить логин",
                "auth_username_label": "Логин",
                "auth_password_label": "Пароль",
                "auth_headers_label": "Пользовательские заголовки",
                "auth_headers_placeholder": "Заголовки, по одному на строку (пример: Cookie: abc=1)",
                "auth_mode_help_none": "Авторизация отключена. Включайте только если источник требует доступ.",
                "auth_mode_help_token": "Укажите bearer-токен и/или пользовательские заголовки, если их требует источник.",
                "auth_mode_help_basic": "Укажите логин/пароль, если их требует источник.",
                "auth_show_password": "Показать пароль",
                "auth_validation_title": "Авторизация",
                "auth_validation_token_or_header_required": "Для этого режима укажите токен или хотя бы один заголовок.",
                "auth_validation_username_required": "Укажите логин для режима логин/пароль.",
                "auth_validation_password_required": "Укажите пароль для режима логин/пароль.",
                "auth_open_settings_hint": "Откройте Настройки, чтобы изменить параметры авторизации.",
                "action_start": "Старт",
                "action_stop": "Стоп",
                "action_preview": "Предпросмотр команды",
                "action_retry_selected": "Перекачать выбранные",
                "action_retry_all": "Перекачать все ошибки/отмены",
                "action_remove_selected": "Удалить выбранные",
                "action_remove_failed": "Удалить ошибки/отмены",
                "action_clear_queue": "Очистить очередь",
                "action_open_file": "Открыть файл",
                "action_open_folder": "Открыть папку",
                "action_priority": "Приоритет",
                "priority_high": "Максимальный",
                "priority_medium": "Средний",
                "priority_low": "Низкий",
                "priority_updated": "Обновлён приоритет для задач: {count} ({priority})",
                "open_file_missing": "Скачанный файл не найден.",
                "open_folder_missing": "Папка загрузки не найдена.",
                "view_toggle_logs": "Показывать логи",
                "view_sort_by_date": "Сортировать по дате добавления",
                "view_sort_by_extension": "Сортировать по расширению",
                "view_sort_by_priority": "Сортировать по приоритету",
            },
        }

    def t(self, key: str, language: str = "en", **kwargs: object) -> str:
        language_map = self._translations.get(language) or self._translations["en"]
        value = language_map.get(key) or self._translations["en"].get(key, key)
        if kwargs:
            try:
                return value.format(**kwargs)
            except Exception:
                return value
        return value
